// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  lebenslauf: dynamic(() => import("./Lebenslauf")),
  referenzen: dynamic(() => import("./Referenzen")),
  skills: dynamic(() => import("./Skills")),
  slider: dynamic(() => import("./Slider")),
  spline: dynamic(() => import("./Spline")),
  text_box: dynamic(() => import("./TextBox")),
  tools: dynamic(() => import("./Tools")),
  video: dynamic(() => import("./Video")),
  widget: dynamic(() => import("./Widget")),
};
